version: '3'
services:
  frontend:
    build:
      context: ./front_end
      dockerfile: Dockerfile
    networks:
      - my_network

  backend:
    build:
      context: ./back_end
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=mongodb://mongodb:27017/react
    networks:
      - my_network

  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    networks:
      - my_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    networks:
      - my_network

networks:
  my_network:

volumes:
  mongodb_data:
